#!/usr/bin/env python3
# /// script
# requires-python = '>=3.12'
# dependencies = [
#   'openai',
# ]
# ///

import argparse
import base64
import logging
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)
logger.addHandler(logging.NullHandler())

PICTURE_PROMPT = (
    'Describe exactly what you see in this image. Be literal and concise. '
    'Describe the visual composition faithfully (e.g., layout, subjects) and '
    'include any visible text, axis labels, legends, or numerical values. If '
    'the image is blank, black, or featureless, state plainly: "Empty" or '
    'describe the color (e.g., "Black bar"). Regardless of content, do NOT '
    'speculate on its purpose or missing context. No filler phrases.'
)


def get_b64_img(image: bytes) -> str:
    encoded = base64.b64encode(image).decode('utf-8')
    return f'data:image/png;base64,{encoded}'


def query_vision_model(client, model, image_bytes, prompt):
    response = client.chat.completions.create(
        model=model,
        messages=[{
            'role': 'user',
            'content': [
                {'type': 'text', 'text': prompt},
                {'type': 'image_url', 'image_url': {
                    'url': get_b64_img(image_bytes),
                }},
            ],
        }],
    )
    content = response.choices[0].message.content.strip()
    # Clean up common markdown code fences
    if content.startswith('```') and content.endswith('```'):
        content = '\n'.join(content.split('\n')[1:-1])
    return content


def process_file(client, filepath: Path, model: str, args):
    """Process a single docx/document file using Pandoc + LLM."""
    with tempfile.TemporaryDirectory(prefix='docs_extract_') as tmp_dir:
        tmp_path = Path(tmp_dir)
        img_out = tmp_path / 'img_out'
        out_md_path = tmp_path / 'output.md'
        logger.debug('Converting %s via Pandoc', filepath.name)
        try:
            subprocess.run([
                'pandoc', str(filepath), '-s', '--extract-media=./img_out',
                '-t', 'markdown', '-o', str(out_md_path),
            ], check=True, capture_output=True, cwd=tmp_path)
        except FileNotFoundError:
            msg = 'Pandoc binary not found on path.'
            raise RuntimeError(msg)
        except subprocess.CalledProcessError as e:
            logger.error('Pandoc failed on %s: %s', filepath.name, e.stderr.decode())
            return None
        if not out_md_path.exists():
            return 'No content generated by Pandoc.'
        text_content = out_md_path.read_text(encoding='utf-8')
        image_regex = r'!\[([^\]]*)\]\((.+?)\)'
        inline_images = list(re.finditer(image_regex, text_content))
        if not inline_images:
            return text_content
        logger.info('Found %d figure(s)/image(s)', len(inline_images))
        markdown_buffer = []
        cursor_idx = 0
        for img_match in inline_images:
            markdown_buffer.append(text_content[cursor_idx:img_match.start()])
            markdown_buffer.append(img_match.group(0))
            rel_path = img_match.group(2).split()[0]
            found_img = None
            matched_filename = os.path.basename(rel_path)
            for root, _, files in os.walk(img_out):
                if matched_filename in files:
                    found_img = Path(root) / matched_filename
                    break
            clean_rel = rel_path.lstrip('./')
            fallback_path = img_out / clean_rel
            if not found_img and fallback_path.exists():
                found_img = fallback_path
            if found_img is not None:
                try:
                    with open(found_img, 'rb') as f:
                        desc = query_vision_model(client, model, f.read(), PICTURE_PROMPT)
                    markdown_buffer.append(f'\n\n> **Figure Description:**\n>\n> {desc}\n')
                except Exception:
                    logger.warning('Failed to describe %s', found_img.name)
            elif not found_img:
                logger.warning('Could not locate extracted image for %s', rel_path)
            cursor_idx = img_match.end()
        markdown_buffer.append(text_content[cursor_idx:])
    return ''.join(markdown_buffer)


def process_directory(args):  # noqa
    from openai import OpenAI

    client = OpenAI(base_url=args.url.rstrip('/') + '/v1', api_key=args.api_key)
    suffix = f'.{args.suffix.lstrip(".")}'
    for input_path in args.inputs:
        target = Path(input_path)
        if target.is_file():
            file_list = [target]
        elif target.is_dir():
            file_list = sorted(target.rglob('*')) if args.recurse else sorted(target.iterdir())
        else:
            continue
        for filepath in file_list:
            if not filepath.is_file():
                continue
            if not str(filepath).endswith((
                '.docx', '.doc', '.rtf', '.odt', '.html',
            )) and filepath not in args.inputs:
                continue
            md_path = filepath.with_suffix(suffix)
            if args.out:
                if os.path.isdir(args.out):
                    md_path = Path(args.out) / md_path.name
                else:
                    md_path = Path(args.out)
            if (not args.overwrite and md_path.exists() and
                    md_path.stat().st_mtime > filepath.stat().st_mtime):
                continue
            if args.list:
                print(f'{filepath} -> {md_path}')
                continue
            try:
                print(filepath)
                description = process_file(client, filepath, args.model, args)
                if description is None:
                    msg = 'Processing yielded no content.'
                    raise RuntimeError(msg)
                if not args.dry_run:
                    md_path.parent.mkdir(parents=True, exist_ok=True)
                    md_path.write_text(description, encoding='utf-8')
                    print(f'Created {md_path.name}')
            except Exception as exc:
                print(f'Failed processing {filepath.name}: {exc}')
                if args.raise_errors:
                    raise


def main():
    parser = argparse.ArgumentParser(
        description='Convert pandoc-readable documents including dox to '
        'Markdown using Docling with LLM-based image descriptions.',
    )
    parser.add_argument(
        'inputs', nargs='+',
        help='One or more files or directories to process.')
    parser.add_argument(
        '--recurse', '-r', action='store_true',
        help='Recurse into input directories')
    parser.add_argument(
        '--suffix', '--ext', default='.description.md',
        help='File extension to use for description files.')
    parser.add_argument(
        '--out', '--output',
        help='If an existing directory, the location to store outputs.  If a '
        'single path or non-existent path, write the first description to '
        'this file and then stop.')
    parser.add_argument(
        '--url', default=os.environ.get('OLLAMA_BASE_URL', 'http://localhost:11434'),
        help='Ollama base URL.  Default %(default)s.')
    parser.add_argument(
        '--api-key', default='ollama',
        help='API key sent to the endpoint.  Default %(default)s.')
    parser.add_argument(
        '--model', '-m', default='qwen2.5vl:7b',
        help='Vision model identifier.  Default %(default)s.')
    parser.add_argument(
        '--overwrite', '-y', action='store_true',
        help='Overwrite existing companion markdown files')
    parser.add_argument(
        '-n', '--dry-run', action='store_true',
        help='Do not actually write markdown files')
    parser.add_argument(
        '--list', '-l', action='store_true',
        help='Just list what files would be processed without actually doing anything.')
    parser.add_argument(
        '--raise', dest='raise_errors', action='store_true',
        help='Raise on errors instead of ignoring them.')
    parser.add_argument(
        '--verbose', '-v', action='count', default=0,
        help='Increase verbosity')
    args = parser.parse_args()
    logger.setLevel(max(1, logging.WARNING - args.verbose * 10))
    logger.addHandler(logging.StreamHandler(sys.stderr))
    process_directory(args)


if __name__ == '__main__':
    main()
